model edited
ykvlv/software-testing pull request #1
Opened 2023-02-11 15:00 UTC by ykvlv

2023-02-19 17:17 UTC, neevink requested changes

2023-02-19 17:17 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +    private int hp;
`uint`?

2023-02-19 17:17 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +    public void changeHpBy(int number) {
Давай сделаем два метода `repair` и `hit`, будем передавать `uint`?
Если у дома `hp == 0`, то пусть `isDestroyed()` возвращает `true`.

Тут можно тест добавить на то, что мы можем продомажить дом, разрушить и починить его.

2023-02-19 17:17 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Bulldozer.java
> +            System.out.printf("%s не может ползать по %s. Здание не разрушено до конца\n", this.getName(), building.getName());
Давай у нас будет метод `isDestroyed()` у здания? Кажется проверка относится больше к зданию, а не к бульдозеру.

Такми образом, сможем тестировать, разрушено ли здание.

2023-02-19 17:17 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Environment.java
> +    public void printScopeOf(Entity entity) {
Пусть возвращает коллекцию, чтобы можно было написать тест по типу: у нас есть окружение, проверяем, что там никого нет, добавляем туда кого-то, проверем, что есть те, кого добавили, удаляем и снова проверяем, что удалаемые удалились.

Функцию переименовать в `scopeOf`, а функцию `printScopeOf` сделать с принтом и в ней уже вызывать `scopeOf`.

2023-02-19 17:17 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Environment.java
> +    public void changeTemperatureBy(int number) {
Давай добавим методы `increaseTempirature(uint)` и `decreaseTempirature(uint)`? И тест на это соответственно.

2023-02-19 17:17 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Environment.java
> +    public void addWeatherPhenomenon(WeatherPhenomenon weatherPhenomenon) {
Пусть возвращает коллекцию + тестик, что можно менять погоду

2023-02-20 04:49 UTC, ykvlv commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +    private int hp;
в Java нету uint)

2023-02-20 05:48 UTC, ykvlv commented on lab1/src/main/java/softwaretesting/lab1/model/Environment.java
> +    public void addWeatherPhenomenon(WeatherPhenomenon weatherPhenomenon) {
Добавил геттер на погодные явления, чтобы можно было проверять

2023-02-20 05:56 UTC, ykvlv commented on lab1/src/main/java/softwaretesting/lab1/model/Environment.java
> +    public void changeTemperatureBy(int number) {
пускай будет один метод. У зданий два. Разнообразие

2023-02-20 06:05 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +        if (hp < 0) throw new NotInAllowedSetException("Урон должен быть больше либо равно нулю");
Класс, тут тест-кейс можно сделать на основе того, что исключение **кидается**

2023-02-20 06:08 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +        return hp > 0;
Поломана логика. Если здание разрушено, то у него hp наоборот `== 0`

2023-02-20 06:09 UTC, ykvlv commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +        return hp > 0;
ой-ей

2023-02-20 06:12 UTC, neevink commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +        if (this.hp < 0) this.hp = Integer.MAX_VALUE;
Блок никогда не выполнится же, зачем он вообще тут? Давай уберём?

2023-02-20 06:13 UTC, ykvlv commented on lab1/src/main/java/softwaretesting/lab1/model/Building.java
> +        if (this.hp < 0) this.hp = Integer.MAX_VALUE;
может произойти переполнение инта) тогда останется MAX_VALUE.

2023-02-20 06:24 UTC, merged